# Generated by Django 4.2.19 on 2025-04-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0003_user_age_user_gender_user_height_user_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.IntegerField(default=180),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.FloatField(default=65),
        ),
    ]
