# Generated by Django 4.2.19 on 2025-04-24 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0004_alter_user_age_alter_user_gender_alter_user_height_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
