# Generated by Django 4.2.19 on 2025-04-24 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0005_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast', to=settings.AUTH_USER_MODEL),
        ),
    ]
