# Generated by Django 4.2.19 on 2025-05-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0006_alter_forecast_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
