# Generated by Django 4.2.19 on 2025-05-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0007_forecast_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_level',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='user',
            name='alcohol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sleep_hours',
            field=models.FloatField(default=8.0),
        ),
        migrations.AddField(
            model_name='user',
            name='smoking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='stress_level',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.FloatField(default=180),
        ),
    ]
